#!/usr/bin/env bash
# Builds the Simpl Courses macOS app (a Safari Web Extension host app).
#
# Requires Xcode (with the Command Line Tools selected) on macOS. Uses
# Apple's safari-web-extension-converter to generate an Xcode project from
# the extension/ folder, then optionally builds it with xcodebuild.
#
#   ./scripts/build-mac-app.sh            # generate macos/Simpl Courses.xcodeproj
#   ./scripts/build-mac-app.sh --build    # …and build the .app (Release, ad-hoc signed)
#   ./scripts/build-mac-app.sh --zip      # …build, and drop SimplCourses-mac-<version>.zip in ~/Downloads
#   ./scripts/build-mac-app.sh --open     # …and open the project in Xcode
#
# Environment overrides:
#   BUNDLE_ID   default: com.simplcourses.app (pick your own, e.g.
#               com.yourname.simplcourses, if Xcode says the default
#               cannot be registered to your team)
#   APP_NAME    default: Simpl Courses
#   OUT_DIR     default: macos
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT_DIR="$ROOT/extension"
OUT_DIR="${OUT_DIR:-$ROOT/macos}"
APP_NAME="${APP_NAME:-Simpl Courses}"
BUNDLE_ID="${BUNDLE_ID:-com.simplcourses.app}"

BUILD=0
OPEN=0
ZIP=0
for arg in "$@"; do
  case "$arg" in
    --build) BUILD=1 ;;
    --zip) BUILD=1; ZIP=1 ;;
    --open) OPEN=1 ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This script must run on macOS (it needs Xcode's safari-web-extension-converter)." >&2
  exit 1
fi
if ! xcode-select -p >/dev/null 2>&1; then
  echo "Xcode is not installed or not selected. Install Xcode from the App Store, open it once, then run:" >&2
  echo "  sudo xcode-select -s /Applications/Xcode.app" >&2
  exit 1
fi
if ! xcrun --find safari-web-extension-converter >/dev/null 2>&1; then
  echo "safari-web-extension-converter not found. Make sure full Xcode (not just the Command Line Tools) is selected." >&2
  exit 1
fi

PROJECT="$OUT_DIR/$APP_NAME/$APP_NAME.xcodeproj"

if [[ -d "$PROJECT" ]]; then
  echo "▶ Xcode project already exists at $PROJECT"
  echo "  The extension files are referenced in place, so edits under extension/ are picked up on the next build."
  echo "  Delete $OUT_DIR to regenerate from scratch."
else
  echo "▶ Generating Xcode project in $OUT_DIR …"
  mkdir -p "$OUT_DIR"
  xcrun safari-web-extension-converter "$EXT_DIR" \
    --project-location "$OUT_DIR" \
    --app-name "$APP_NAME" \
    --bundle-identifier "$BUNDLE_ID" \
    --macos-only \
    --no-prompt \
    --no-open \
    --force
fi

# Xcode refuses to embed the extension unless its bundle identifier is the
# app's identifier plus ".Extension". Normalise both so a stray edit or a
# converter quirk cannot break the build.
PBXPROJ="$PROJECT/project.pbxproj"
# The converter pins the minimum macOS to the machine that generated the project, so an app
# built on a new macOS would refuse to open on older ones. Pin it low instead (MACOS_MIN to
# override): the extension needs Safari 16.4 or later, which Ventura carries.
MACOS_MIN="${MACOS_MIN:-13.0}"
if [[ -f "$PBXPROJ" ]]; then
  sed -i.bak -E \
    -e "/PRODUCT_BUNDLE_IDENTIFIER = [^;]*[Ee]xtension[^;]*;/s/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID}.Extension;/" \
    -e "/PRODUCT_BUNDLE_IDENTIFIER = [^;]*[Ee]xtension[^;]*;/!s/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/" \
    -e "s/MACOSX_DEPLOYMENT_TARGET = [^;]+;/MACOSX_DEPLOYMENT_TARGET = ${MACOS_MIN};/" \
    -e "s/^(\t*)objectVersion = [0-9]+;/\1objectVersion = 77;/" \
    "$PBXPROJ"
  # (objectVersion 77 is Xcode 16's project format: a project generated by a beta Xcode would
  # otherwise be "a future project file format" to the release Xcode that Xcode Cloud runs)
  rm -f "$PBXPROJ.bak"
  # App Store rules: the app's Info.plist needs a category, and the app's version follows the extension's.
  VERSION="$(python3 -c "import json;print(json.load(open('$EXT_DIR/manifest.json'))['version'])" 2>/dev/null || echo 1.0)"
  sed -i.bak -E "s/MARKETING_VERSION = [^;]+;/MARKETING_VERSION = ${VERSION};/" "$PBXPROJ" && rm -f "$PBXPROJ.bak"
  APP_PLIST="$(dirname "$PROJECT")/$APP_NAME/Info.plist"
  if [[ -f "$APP_PLIST" ]] && ! /usr/libexec/PlistBuddy -c "Print :LSApplicationCategoryType" "$APP_PLIST" >/dev/null 2>&1; then
    /usr/libexec/PlistBuddy -c "Add :LSApplicationCategoryType string public.app-category.education" "$APP_PLIST"
  fi
  # export compliance answered up front (only HTTPS): a TestFlight build otherwise waits at "Missing Compliance"
  if [[ -f "$APP_PLIST" ]] && ! /usr/libexec/PlistBuddy -c "Print :ITSAppUsesNonExemptEncryption" "$APP_PLIST" >/dev/null 2>&1; then
    /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$APP_PLIST"
  fi
  # Xcode Cloud: number each cloud build from CI_BUILD_NUMBER, so every upload is newer than the last.
  CI_DIR="$(dirname "$PROJECT")/ci_scripts"
  mkdir -p "$CI_DIR"
  cat > "$CI_DIR/ci_pre_xcodebuild.sh" <<'CIEOF'
#!/bin/sh
# Xcode Cloud runs this before xcodebuild: stamp the build number so TestFlight accepts every upload.
set -e
cd "$CI_PRIMARY_REPOSITORY_PATH/macos/Simpl Courses"
if [ -n "${CI_BUILD_NUMBER:-}" ]; then xcrun agvtool new-version -all "$CI_BUILD_NUMBER"; fi
CIEOF
  chmod +x "$CI_DIR/ci_pre_xcodebuild.sh"
  echo "▶ Bundle identifiers:"
  grep -o 'PRODUCT_BUNDLE_IDENTIFIER = [^;]*' "$PBXPROJ" | sort -u | sed 's/^/    /'
  echo "▶ Minimum macOS: $MACOS_MIN (MACOS_MIN=… to change)"
fi

if [[ "$BUILD" == "1" ]]; then
  echo "▶ Building $APP_NAME.app (Release, ad-hoc signed) …"
  DERIVED="$OUT_DIR/DerivedData"
  xcodebuild \
    -project "$PROJECT" \
    -scheme "$APP_NAME" \
    -configuration Release \
    -derivedDataPath "$DERIVED" \
    CODE_SIGN_IDENTITY="-" \
    CODE_SIGNING_REQUIRED=NO \
    CODE_SIGNING_ALLOWED=NO \
    MACOSX_DEPLOYMENT_TARGET="$MACOS_MIN" \
    build | tail -n 5
  APP_PATH="$DERIVED/Build/Products/Release/$APP_NAME.app"
  if [[ -d "$APP_PATH" ]]; then
    mkdir -p "$OUT_DIR/build"
    rm -rf "$OUT_DIR/build/$APP_NAME.app"
    cp -R "$APP_PATH" "$OUT_DIR/build/"
    # Ad-hoc sign the app and the extension inside it. An unsigned app cannot run at all on
    # Apple silicon (macOS reports it as "damaged"); an ad-hoc-signed one runs after Gatekeeper's
    # one-time "Open Anyway" on a Mac it was copied to.
    codesign --force --deep --sign - "$OUT_DIR/build/$APP_NAME.app"
    echo
    echo "✅ Built: $OUT_DIR/build/$APP_NAME.app (ad-hoc signed)"
    echo "   Next: open the app once, then enable Simpl Courses in Safari → Settings → Extensions."
    echo "   Unsigned builds also need: Safari → Settings → Developer → Allow unsigned extensions."
    echo "   On another Mac: unzip, move to Applications, then System Settings → Privacy & Security → Open Anyway"
    echo "   (or: xattr -dr com.apple.quarantine \"/Applications/$APP_NAME.app\")."
    if [[ "$ZIP" == "1" ]]; then
      VERSION="$(python3 -c "import json;print(json.load(open('$EXT_DIR/manifest.json'))['version'])" 2>/dev/null || echo dev)"
      ZIP_PATH="$HOME/Downloads/SimplCourses-mac-$VERSION.zip"
      rm -f "$ZIP_PATH"
      ditto -c -k --keepParent "$OUT_DIR/build/$APP_NAME.app" "$ZIP_PATH"
      echo
      echo "📦 Zip: $ZIP_PATH"
    fi
  else
    echo "Build finished but the app was not found at $APP_PATH" >&2
    exit 1
  fi
fi

if [[ "$OPEN" == "1" ]]; then
  open "$PROJECT"
fi
